// models/Order.js
const mongoose = require("mongoose");

const GoodsListSchema = new mongoose.Schema({
  GoodsName: String,
  GoodsUnit: String,
  Note: String,
  Quantity: Number,
  QuantityFact: Number,
  HasPhoto: Boolean,
  LoadStatus: String,
});

const CustomFieldSchema = new mongoose.Schema({
  Id: String,
  Label: String,
});

const OrderSchema = new mongoose.Schema({
  Number: String,
  Date: Date,
  SeqNumber: Number,
  RouteNumber: String,
  RouteDate: Date,
  RouteStatus: String,
  DriverLogin: String,
  DriverName: String,
  DriverNumber: Number,
  DriverVehicle: String,
  Type: Number,
  ShipperId: String,
  Shipper: String,
  DepotId: String,
  Depot: String,
  Client: String,
  Address: String,
  AddressLat: Number,
  AddressLon: Number,
  AddressZone: String,
  TimeSlotFrom: Date,
  TimeSlotTo: Date,
  ServiceTime: Number,
  Note: String,
  ContactName: String,
  Phone: String,
  Email: String,
  Weight: Number,
  Volume: Number,
  Pallets: Number,
  COD: Number,
  CODActual: String,
  StatusId: Number,
  Status: String,
  StatusLat: Number,
  StatusLon: Number,
  DriverComment: String,
  HasSignaturePhoto: Boolean,
  HasPhoto: Boolean,
  Photos: [String],
  StatusDate: Date,
  ETA: Date,
  ArrivedDate: Date,
  DepartedDate: Date,
  GoodsList: [GoodsListSchema],
  ReportUrl: String,
  CustomFields: [CustomFieldSchema],
  Barcode: String,
  Scanned: Boolean,
  TrackKey: String,
  TrackId: String,
  TrackLink: String,
  LoadStatus: String,
  LoadDate: Date,
  ChangeDate: Date,
  CreateSource: String,
  DistanceFromDepotPlan: Number,
  Pin: String,
  CreateDateUtc: Date,
});

module.exports = mongoose.model("Order", OrderSchema);
